M48
; DRILL file {KiCad 7.0.7} date Wed Nov  1 03:39:06 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-01T03:39:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0510
%
G90
G05
T1
X3.7252Y-2.0591
X3.9528Y-2.0591
T2
X5.0742Y-2.4583
X5.1142Y-2.2583
X5.1542Y-2.4583
T3
X3.9307Y-2.8315
X4.6Y-2.8315
T0
M30
